project: default
source:
  repoURL: 'https://github.com/iliusa77/k8s-argocd.git'
  path: application/guestbook/manifests
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - CreateNamespace=true
